# encoding: utf-8

AdminUser.create([
  { :email => "alpha@alpha.com", :encrypted_password => "$2a$10$Nswd4B/qEB0k8ZWKf5cXz.djaEpnd7enh2/vu6BVAKUGyqNV.Ozfq", :reset_password_token => "4JHE1C2BLVmHjC4YyXnp", :reset_password_sent_at => "2013-05-25 18:21:27", :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-05-25 18:23:25", :last_sign_in_at => "2013-05-25 18:23:25", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-05-25 18:21:27", :updated_at => "2013-05-25 18:23:25" }
], :without_protection => true )

ProjectGroup.create([
  { :name => "Web", :created_at => "2013-05-25 18:21:28", :updated_at => "2013-05-25 18:21:28" },
  { :name => "Diseño", :created_at => "2013-05-25 18:21:28", :updated_at => "2013-05-25 18:21:28" },
  { :name => "Ebooks", :created_at => "2013-05-25 18:21:28", :updated_at => "2013-05-25 18:21:28" }
], :without_protection => true )

Project.create([
  { :name => "Bibliomula", :title => "Bibliomula", :title_link => "http://bibliomula.com", :subtitle => "Revista de literatura", :img_small => "/assets/portfolio/thumbs/portfolio_small_01.png", :zoom_details => "Bibliomula - Revista de literatura", :img_large => "/assets/portfolio/originals/portfolio_large_01.png", :project_group_id => 1, :created_at => "2013-05-25 18:21:28", :updated_at => "2013-05-25 18:21:28" },
  { :name => "Pickista", :title => "Pickista", :title_link => "http://pickista.com", :subtitle => "", :img_small => "/assets/portfolio/thumbs/portfolio_small_01_1.png", :zoom_details => "Pickista - Crea encuestas graficas para que tus amigos te ayuden", :img_large => "/assets/portfolio/originals/portfolio_large_01_1.png", :project_group_id => 1, :created_at => "2013-05-25 18:21:28", :updated_at => "2013-05-25 18:21:28" },
  { :name => "The Counterpoint", :title => "The Counterpoint", :title_link => "http://the-counterpoint.com", :subtitle => "", :img_small => "/assets/portfolio/thumbs/portfolio_small_02.jpg", :zoom_details => "The Counterpoint - Sistema web de discuciones inteligente", :img_large => "/assets/portfolio/originals/portfolio_large_02.jpg", :project_group_id => 1, :created_at => "2013-05-25 18:21:28", :updated_at => "2013-05-25 18:21:28" },
  { :name => "Portal Universidad de Los Andes", :title => "Universidad de Los Andes", :title_link => "http://www.ula.ve/", :subtitle => "", :img_small => "/assets/portfolio/thumbs/portfolio_small_03.jpg", :zoom_details => "Portal web de la Universidad de Los Andes", :img_large => "/assets/portfolio/originals/portfolio_large_03.jpg", :project_group_id => 1, :created_at => "2013-05-25 18:21:28", :updated_at => "2013-05-25 18:21:28" },
  { :name => "Parenting Bridge", :title => "Parenting Bridge", :title_link => "http://parentingbridge.com", :subtitle => "", :img_small => "/assets/portfolio/thumbs/portfolio_small_04.jpg", :zoom_details => "Parenting Bridge - Aplicacion web para gestionar la custodia de hijos de padres divorciados", :img_large => "/assets/portfolio/originals/portfolio_large_04.jpg", :project_group_id => 1, :created_at => "2013-05-25 18:21:28", :updated_at => "2013-05-25 18:21:28" },
  { :name => "Mil1", :title => "Mil1 (Mil y un libros)", :title_link => "http://miluno.alphadeville.com", :subtitle => "Calculo de libros en lo que resta de vida", :img_small => "/assets/portfolio/thumbs/portfolio_small_05.jpg", :zoom_details => "Mil1 - Calculo de libros en lo que resta de vida", :img_large => "/assets/portfolio/originals/portfolio_large_05.jpg", :project_group_id => 1, :created_at => "2013-05-25 18:25:46", :updated_at => "2013-05-25 18:25:46" },
  { :name => "the_country_identity", :title => "the_country_identity", :title_link => "http://p1nox.github.io/the_country_identity/", :subtitle => "Gema RoR - Crawler del CIA Factbook", :img_small => "/assets/portfolio/thumbs/portfolio_small_06.png", :zoom_details => "Gema RoR the_country_identity - Crawler del CIA Factbook", :img_large => "/assets/portfolio/originals/portfolio_large_06.png", :project_group_id => 1, :created_at => "2013-05-25 18:27:24", :updated_at => "2013-05-25 18:27:24" },
  { :name => "Violencia en el noviazgo", :title => "Violencia en el noviazgo", :title_link => "#", :subtitle => "Campaña para la prevención de la...", :img_small => "/assets/portfolio/thumbs/portfolio_small_10.jpg", :zoom_details => "Violencia en el noviazgo - Campaña para la prevención de la violencia en el noviazgo", :img_large => "/assets/portfolio/originals/portfolio_large_10.jpg", :project_group_id => 2, :created_at => "2013-05-25 18:28:56", :updated_at => "2013-05-25 18:28:56" },
  { :name => "Souvenir Venezolano", :title => "Souvenir Venezolano", :title_link => "#", :subtitle => "Tarjetas postales desde una...", :img_small => "/assets/portfolio/thumbs/portfolio_small_11.jpg", :zoom_details => "Tarjetas postales desde una perspectiva", :img_large => "/assets/portfolio/originals/portfolio_large_11.jpg", :project_group_id => 2, :created_at => "2013-05-25 18:30:10", :updated_at => "2013-05-25 18:30:10" },
  { :name => "Editorial revista Watt", :title => "Editorial revista Watt", :title_link => "#", :subtitle => "Rediseño Editorial para una...", :img_small => "/assets/portfolio/thumbs/portfolio_small_12.jpg", :zoom_details => "Rediseño Editorial para una doble página", :img_large => "/assets/portfolio/originals/portfolio_large_12.jpg", :project_group_id => 2, :created_at => "2013-05-25 18:31:14", :updated_at => "2013-05-25 18:31:14" },
  { :name => "Logotipo Café Origami", :title => "Logotipo Café Origami", :title_link => "#", :subtitle => "Logotipo para Café Origami...", :img_small => "/assets/portfolio/thumbs/portfolio_small_13.jpg", :zoom_details => "Logotipo para Café Origami, Bogotá-Colombia", :img_large => "/assets/portfolio/originals/portfolio_large_13.jpg", :project_group_id => 2, :created_at => "2013-05-25 18:32:20", :updated_at => "2013-05-25 18:32:20" },
  { :name => "Background Universidad Javeriana", :title => "Background Universidad Javeriana", :title_link => "#", :subtitle => "Background ilustrado para el...", :img_small => "/assets/portfolio/thumbs/portfolio_small_14.jpg", :zoom_details => "Background ilustrado para el site de Centro Ático, Universidad Javeriana, Bogotá-Colombia", :img_large => "/assets/portfolio/originals/portfolio_large_14.jpg", :project_group_id => 2, :created_at => "2013-05-25 18:33:18", :updated_at => "2013-05-25 18:33:18" },
  { :name => "Logotipo Endógeno TR", :title => "Logotipo Endógeno TR", :title_link => "#", :subtitle => "Logotipo para la agencia de...", :img_small => "/assets/portfolio/thumbs/portfolio_small_15.jpg", :zoom_details => "Logotipo para la agencia de turismo responsable Endógeno, Mérida Venezuela", :img_large => "/assets/portfolio/originals/portfolio_large_15.jpg", :project_group_id => 2, :created_at => "2013-05-25 18:34:09", :updated_at => "2013-05-25 18:34:09" },
  { :name => "Antología japonesa", :title => "Antología japonesa", :title_link => "http://bibliomula.org/index.php/posgutenberg/el-evangelio-del-ebook/50-bibliomula-org-presenta-antologia-poesia-contemporanea-de-japon.html", :subtitle => "Descarga desde Bibliomula", :img_small => "/assets/portfolio/thumbs/portfolio_small_07.jpg", :zoom_details => "50 años de narrativa venezolana o manual para no perderse en Caracas", :img_large => "/assets/portfolio/originals/portfolio_large_07.jpg", :project_group_id => 3, :created_at => "2013-05-25 18:36:14", :updated_at => "2013-05-25 18:40:45" },
  { :name => "Narrativa venezolana", :title => "Narrativa venezolana", :title_link => "http://bibliomula.org/index.php/archivo/34-ediciones-anterioes/3ra-e…-50-anos-de-narrativa-venezolana-o-manual-para-no-perderse-en-caracas.html", :subtitle => "Descarga desde Bibliomula", :img_small => "/assets/portfolio/thumbs/portfolio_small_08.jpg", :zoom_details => "50 años de narrativa venezolana o manual para no perderse en Caracas", :img_large => "/assets/portfolio/originals/portfolio_large_08.jpg", :project_group_id => 3, :created_at => "2013-05-25 18:37:15", :updated_at => "2013-05-25 18:37:15" },
  { :name => "Por qué las librerías", :title => "Por qué las librerías", :title_link => "http://bibliomula.org/index.php/archivo/37-ediciones-anterioes/4ta-edicion/120-junio-2012-por-que-las-librerias.html", :subtitle => "Descarga desde Bibliomula", :img_small => "/assets/portfolio/thumbs/portfolio_small_09.jpg", :zoom_details => "Por qué las librerías: Porque a veces los libros te encuentran a ti y no tu a ellos", :img_large => "/assets/portfolio/originals/portfolio_large_09.jpg", :project_group_id => 3, :created_at => "2013-05-25 18:38:17", :updated_at => "2013-05-25 18:38:17" }
], :without_protection => true )
